### ISSUE TITLE
Error on addons grid styles, looks too close to each other

### ISSUE THREAD

**Issue by LeoCaprile** [blueprint-site/blueprint-site.github.io#14]
<img width="1474" alt="image" src="https://github.com/blueprint-site/blueprint-site.github.io/assets/71847541/d539322a-335c-4d8d-881b-7b7c364b902c">

**Comment by JavaBoii** [comment]
Has this issue been fixed? @LeoCaprile

**Comment by yehorscode** [comment]
I think It has been fixed
