### ISSUE TITLE
Use a proper UI framework

### ISSUE THREAD

**Issue by LeoCaprile** [blueprint-site/blueprint-site.github.io#15]
The project isn't scalable if we use plain html, css, js. 
We should port it to some framework like svelte, vuejs or react.

**Comment by LeoCaprile** [comment]
we are working on it, the framework chosed was react.

**Comment by JavaBoii** [comment]
@LeoCaprile How far are we with this?

**Comment by yehorscode** [comment]
With rewriting with React? Pretty far

**Comment by yehorscode** [comment]
Becasue we are already using react in a new tree i close this issue
