### ISSUE TITLE
Implement an user-system

### ISSUE THREAD

**Issue by TheReal-Flo** [blueprint-site/blueprint-site.github.io#53]
Implement an user-system
- [ ] Login-Page
- [ ] Profile-Page
- [ ] Settings-Page

This is required to manage and restrict access to the API

**Comment by JavaBoii** [comment]
What exactly do you mean by access to the API. Who is getting access? @TheReal-Flo

**Comment by TheReal-Flo** [comment]
The users using the site for example, to download and upload schematics, like schematics, vote in the awards, subscribe to a newsletter...

**Comment by LeoCaprile** [comment]
I think we could manage it with some auth library, like [lucia-auth](https://lucia-auth.com/getting-started/express), in the front, maybe use some library too, or roll our own.

> What exactly do you mean by access to the API. Who is getting access? @TheReal-Flo

Restricting access to the API by requiring authorization in every request, the authorization should come after the user authenticates.

**Comment by JavaBoii** [comment]
@LeoCaprile i thought more of passport https://www.npmjs.com/package/passport
What do you think

**Comment by TheReal-Flo** [comment]
> @LeoCaprile i thought more of passport https://www.npmjs.com/package/passport
> 
> What do you think

Yeah, me too. I have already got an package with predesigned login buttons for a lot of services

**Comment by LeoCaprile** [comment]
> @LeoCaprile i thought more of passport https://www.npmjs.com/package/passport What do you think

I used passport before in work, was not a good experience to be honest. :(

I'm looking forward to use something more modern and with good docs.
I used lucia-auth also, and was a smoth experience.
But if you guys are experienced with passportjs, I'm okay with going with it.

**Comment by JavaBoii** [comment]
@LeoCaprile 
oh no, i will gladly take someones opinion with experience over mine hahah. Then lets go with lucia-auth

**Comment by TheReal-Flo** [comment]
Idk, lucia-auth looks kinda "incomplete" to me, also it would be a hassle to implement oauth there. We should go with Passport, it's easy to use and should also be easy to learn for @LeoCaprile

**Comment by LeoCaprile** [comment]
> Idk, lucia-auth looks kinda "incomplete" to me, also it would be a hassle to implement oauth there. We should go with Passport, it's easy to use and should also be easy to learn for @LeoCaprile

No worries, lets go with Passport then!
