### ISSUE TITLE
Random button filtering

### ISSUE THREAD

**Issue by DadamaldaDad** [blueprint-site/blueprint-site.github.io#55]
Would be awesome if the random button respect filters. It currently doesn't care that I filtered for fabric 1.20.1 and shows all addons.

**Comment by yehorscode** [comment]
My thought on this:
1. I mean it would be nice to have the filters, but random button is just for random addons nothing else. No filters and no parameters. If it isn't avaible for your version - sad, click again and move on
2. But filters are good! I don't want to click the button 10 times!
My brain is split in half rn
