### ISSUE TITLE
Schematic3DViewer laggin with > 1000 blocks loaded

### ISSUE THREAD

**Issue by LeoCaprile** [blueprint-site/blueprint-site.github.io#57]
@TheReal-Flo reported this issue, when we have a .nbt file with a lot of blocks the rendering with threejs is really slow, reading the docs here's are some useful corrections to make the rendering more fluid.
I'll be working on this issue.

Task list:
- [x] Laggin when loading a File with more that 10.000 blocks
  - [Instancing similar blocks instead of recreate it each time. ](https://docs.pmnd.rs/react-three-fiber/advanced/scaling-performance#instancing)
  - [Level of detail](https://docs.pmnd.rs/react-three-fiber/advanced/scaling-performance#level-of-detail)
  - [Considering common pitfalls](https://docs.pmnd.rs/react-three-fiber/advanced/pitfalls)

**Comment by LeoCaprile** [comment]
using instancedMesh fix the problem

**Comment by JavaBoii** [comment]
@LeoCaprile Are you currently working on it?

**Comment by LeoCaprile** [comment]
> @LeoCaprile Are you currently working on it?

Yes! MR opened
