### ISSUE TITLE
Re-scan required

### ISSUE THREAD

**Issue by DadamaldaDad** [blueprint-site/blueprint-site.github.io#76]
Hasn't even been a month and a re-scan is already required.

Differences to Modrinth I noticed:
New mods:
Create: Nuke
Create: Cards
Create: Data and Plots
Ported to Fabric:
Create: Railways Navigator

This list is only intended to prove a point, I only checked mods for Fabric 1.20.1, but many more have released

**Comment by yehorscode** [comment]
Okay, i will do It tomorrow with all-new and improved version

**Comment by DadamaldaDad** [comment]
Thanks.
I never noticed how fast the create community makes addons.

**Comment by LeoCaprile** [comment]
This should be a good reason to implement a automatic scanner in our API, what do you think guys @JavaBoii, @TheReal-Flo, @yehorscode  ?

**Comment by yehorscode** [comment]
No, overloading the Modrinth API is a bad thing, and i will not support that

**Comment by LeoCaprile** [comment]
> No, overloading the Modrinth API is a bad thing, and i will not support that

I didn't mean overloading the modrinth API, just making one automatic request each day to update a json file in our API that serves the addons info, in that way we don't reach the modrinth API limit.

**Comment by yehorscode** [comment]
That would require a rewrite of how the data is gathered

**Comment by LeoCaprile** [comment]
> That would require a rewrite of how the data is gathered

mmm it depends, we could keep the same format as we have now, the only thing that changes it's that we call our API instead of a JSON file in the project.

This is the mental model I have:
![image](https://github.com/blueprint-site/blueprint-site.github.io/assets/71847541/c39136b5-97e9-4039-8220-f69a3c6b39c5)

**Comment by yehorscode** [comment]
Hmmm, interesting. Now the script to gather data heavily depends on manuał user input (i manually check around 50 results)

**Comment by yehorscode** [comment]
I am closing this issue because #78 is merged into main and deployed
