### ISSUE TITLE
3D viewer not showing anything with an Adblock

### ISSUE THREAD

**Issue by yehorscode** [blueprint-site/blueprint-site.github.io#86]
# Issue
3D viewer not showing the 3d thingy when adblocker is installed
# Why?
Adblock is blocking the 3d view and thinks It is an ad
# What adblocker did i use?
UBlock origin | Firefox on Gnu/Linux (Linux Mint based on Ubuntu based on Debian)

**Comment by TheReal-Flo** [comment]
You should probably switch to [Hannah Montana Linux](https://hannahmontana.sourceforge.net) xD
