### ISSUE TITLE
Dark Mode on home page breaks for-creators coloring

### ISSUE THREAD

**Issue by yehorscode** [blueprint-site/blueprint-site.github.io#97]
When applied darkmode stuff at for-creators such as texts are colored white instead of dark
this bug report wouldn't exist if i didn't push the changes :cry:

first seen in #90 i think

**Comment by TheReal-Flo** [comment]
This issue happens because the color scheme gets changed for the entire page, not for single pages. Possible fixes:
- Change background for element, so the contrast looks better (preferred)
- Override the font color for the element

**Comment by yehorscode** [comment]
I think I fixed it but I am not sure

**Comment by yehorscode** [comment]
It is still present will be fixed in v2
