### ISSUE TITLE
NeoForge not showing (random addon section on homepage)

### ISSUE THREAD

**Issue by yehorscode** [blueprint-site/blueprint-site.github.io#99]
NeoForge icon isn't showing i have no idea why pls help

**Comment by uberswe** [comment]
<img width="655" alt="839bd62a6eb72fefb4783d7d16894c4d" src="https://github.com/blueprint-site/blueprint-site.github.io/assets/1903284/82f5dc8f-95a8-4a41-aaf9-c1018c52cc34">

If you mean this section, it's working fine for me

**Comment by yehorscode** [comment]
> <img width="655" alt="839bd62a6eb72fefb4783d7d16894c4d" src="https://github.com/blueprint-site/blueprint-site.github.io/assets/1903284/82f5dc8f-95a8-4a41-aaf9-c1018c52cc34">
> 
> If you mean this section, it's working fine for me

(hi uberswe!) I forgot to mention that this issue affects the react-refactor branch with the react version of the site 😅
